/** Devises ISO 4217 courantes (code, libellé, symbole indicatif) */
export type IsoCurrency = { code: string; name: string; symbol: string }

export const ISO_4217_CURRENCIES: IsoCurrency[] = [
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'USD', name: 'Dollar US', symbol: '$' },
  { code: 'GBP', name: 'Livre sterling', symbol: '£' },
  { code: 'CHF', name: 'Franc suisse', symbol: 'CHF' },
  { code: 'CAD', name: 'Dollar canadien', symbol: 'C$' },
  { code: 'AUD', name: 'Dollar australien', symbol: 'A$' },
  { code: 'JPY', name: 'Yen', symbol: '¥' },
  { code: 'CNY', name: 'Yuan', symbol: '¥' },
  { code: 'HKD', name: 'Dollar HK', symbol: 'HK$' },
  { code: 'SGD', name: 'Dollar singapourien', symbol: 'S$' },
  { code: 'NZD', name: 'Dollar néo-zélandais', symbol: 'NZ$' },
  { code: 'SEK', name: 'Couronne suédoise', symbol: 'kr' },
  { code: 'NOK', name: 'Couronne norvégienne', symbol: 'kr' },
  { code: 'DKK', name: 'Couronne danoise', symbol: 'kr' },
  { code: 'PLN', name: 'Zloty', symbol: 'zł' },
  { code: 'CZK', name: 'Couronne tchèque', symbol: 'Kč' },
  { code: 'HUF', name: 'Forint', symbol: 'Ft' },
  { code: 'RON', name: 'Leu roumain', symbol: 'lei' },
  { code: 'BGN', name: 'Lev', symbol: 'лв' },
  { code: 'TRY', name: 'Lire turque', symbol: '₺' },
  { code: 'RUB', name: 'Rouble', symbol: '₽' },
  { code: 'UAH', name: 'Hryvnia', symbol: '₴' },
  { code: 'ILS', name: 'Shekel', symbol: '₪' },
  { code: 'AED', name: 'Dirham UAE', symbol: 'د.إ' },
  { code: 'SAR', name: 'Riyal saoudien', symbol: '﷼' },
  { code: 'QAR', name: 'Riyal qatari', symbol: '﷼' },
  { code: 'KWD', name: 'Dinar koweïtien', symbol: 'د.ك' },
  { code: 'BHD', name: 'Dinar bahreïni', symbol: 'د.ب' },
  { code: 'OMR', name: 'Rial omanais', symbol: '﷼' },
  { code: 'INR', name: 'Roupie indienne', symbol: '₹' },
  { code: 'PKR', name: 'Roupie pakistanaise', symbol: '₨' },
  { code: 'BDT', name: 'Taka', symbol: '৳' },
  { code: 'LKR', name: 'Roupie srilankaise', symbol: '₨' },
  { code: 'THB', name: 'Baht', symbol: '฿' },
  { code: 'VND', name: 'Dong', symbol: '₫' },
  { code: 'IDR', name: 'Roupie indonésienne', symbol: 'Rp' },
  { code: 'MYR', name: 'Ringgit', symbol: 'RM' },
  { code: 'PHP', name: 'Peso philippin', symbol: '₱' },
  { code: 'KRW', name: 'Won', symbol: '₩' },
  { code: 'TWD', name: 'Dollar taïwanais', symbol: 'NT$' },
  { code: 'MXN', name: 'Peso mexicain', symbol: 'MX$' },
  { code: 'BRL', name: 'Real', symbol: 'R$' },
  { code: 'ARS', name: 'Peso argentin', symbol: '$' },
  { code: 'CLP', name: 'Peso chilien', symbol: '$' },
  { code: 'COP', name: 'Peso colombien', symbol: '$' },
  { code: 'PEN', name: 'Sol', symbol: 'S/' },
  { code: 'ZAR', name: 'Rand', symbol: 'R' },
  { code: 'EGP', name: 'Livre égyptienne', symbol: 'E£' },
  { code: 'NGN', name: 'Naira', symbol: '₦' },
  { code: 'KES', name: 'Shilling kényan', symbol: 'KSh' },
  { code: 'GHS', name: 'Cedi', symbol: '₵' },
  { code: 'XOF', name: 'Franc CFA (BCEAO)', symbol: 'CFA' },
  { code: 'XAF', name: 'Franc CFA (BEAC)', symbol: 'FCFA' },
  { code: 'MAD', name: 'Dirham marocain', symbol: 'د.م.' },
  { code: 'TND', name: 'Dinar tunisien', symbol: 'د.ت' },
  { code: 'DZD', name: 'Dinar algérien', symbol: 'د.ج' },
  { code: 'CDF', name: 'Franc congolais', symbol: 'FC' },
  { code: 'RWF', name: 'Franc rwandais', symbol: 'FRw' },
]
